# Generated by Django 4.0.4 on 2022-06-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='update',
            new_name='updated',
        ),
    ]
